---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.17.2
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

# Advanced operations

## Polynomials

NumPy also contains polynomials in different bases:

For example, $3x^2 + 2x - 1$:

```{python}
import numpy as np
import matplotlib.pyplot as plt
```

```{python}
p = np.poly1d([3, 2, -1])
p(0)
```

```{python}
p.roots
```

```{python}
p.order
```

```{python}
x = np.linspace(0, 1, 20)
rng = np.random.default_rng()
y = np.cos(x) + 0.3*rng.random(20)
p = np.poly1d(np.polyfit(x, y, 3))

t = np.linspace(0, 1, 200) # use a larger number of points for smoother plotting
plt.plot(x, y, 'o', t, p(t), '-');
```

See <https://numpy.org/doc/stable/reference/routines.polynomials.poly1d.html>
for more.

### More polynomials (with more bases)

NumPy also has a more sophisticated polynomial interface, which supports
e.g. the Chebyshev basis.

$3x^2 + 2x - 1$:

```
>>> p = np.polynomial.Polynomial([-1, 2, 3]) # coefs in different order!
>>> p(0)
np.float64(-1.0)
>>> p.roots()
array([-1.        ,  0.33333333])
>>> p.degree()  # In general polynomials do not always expose 'order'
2
```

Example using polynomials in Chebyshev basis, for polynomials in
range `[-1, 1]`:

```
>>> x = np.linspace(-1, 1, 2000)
>>> rng = np.random.default_rng()
>>> y = np.cos(x) + 0.3*rng.random(2000)
>>> p = np.polynomial.Chebyshev.fit(x, y, 90)

>>> plt.plot(x, y, 'r.')
[<matplotlib.lines.Line2D object at ...>]
>>> plt.plot(x, p(x), 'k-', lw=3)
[<matplotlib.lines.Line2D object at ...>]
```

```{image} auto_examples/images/sphx_glr_plot_chebyfit_001.png
:align: center
:target: auto_examples/plot_chebyfit.html
:width: 50%
```

The Chebyshev polynomials have some advantages in interpolation.

## Loading data files

### Text files

Example: {download}`populations.txt <../../data/populations.txt>`:

```{eval-rst}
.. include:: ../../data/populations.txt
    :end-line: 5
    :literal:
```

```
>>> data = np.loadtxt('data/populations.txt')
>>> data
array([[  1900.,  30000.,   4000.,  48300.],
       [  1901.,  47200.,   6100.,  48200.],
       [  1902.,  70200.,   9800.,  41500.],
...
```

```
>>> np.savetxt('pop2.txt', data)
>>> data2 = np.loadtxt('pop2.txt')
```

:::{note}
If you have a complicated text file, what you can try are:

- `np.genfromtxt`
- Using Python's I/O functions and e.g. regexps for parsing
  (Python is quite well suited for this)
:::

### Reminder: Navigating the filesystem with Jupyter and IPython

Show current directory:

```{python}
pwd
```

Change to `data` subdirectory:

```{python}
cd data
```

Show filesystem listing for current directory:

```{python}
ls
```

Change back to containing directory.

```{python}
cd ..
```

### Images

Using Matplotlib:

```
>>> img = plt.imread('data/elephant.png')
>>> img.shape, img.dtype
((200, 300, 3), dtype('float32'))
>>> plt.imshow(img)
<matplotlib.image.AxesImage object at ...>
>>> plt.savefig('plot.png')

>>> plt.imsave('red_elephant.png', img[:,:,0], cmap=plt.cm.gray)
```

```{image} auto_examples/images/sphx_glr_plot_elephant_001.png
:align: center
:target: auto_examples/plot_elephant.html
:width: 50%
```

This saved only one channel (of RGB):

```
>>> plt.imshow(plt.imread('red_elephant.png'))
<matplotlib.image.AxesImage object at ...>
```

```{image} auto_examples/images/sphx_glr_plot_elephant_002.png
:align: center
:target: auto_examples/plot_elephant.html
:width: 50%
```

Other libraries:

```
>>> import imageio.v3 as iio
>>> iio.imwrite('tiny_elephant.png', (img[::6,::6] * 255).astype(np.uint8))
>>> plt.imshow(plt.imread('tiny_elephant.png'), interpolation='nearest')
<matplotlib.image.AxesImage object at ...>
```

```{image} auto_examples/images/sphx_glr_plot_elephant_003.png
:align: center
:target: auto_examples/plot_elephant.html
:width: 50%
```

### NumPy's own format

NumPy has its own binary format, not portable but with efficient I/O:

```
>>> data = np.ones((3, 3))
>>> np.save('pop.npy', data)
>>> data3 = np.load('pop.npy')
```

### Well-known (& more obscure) file formats

- HDF5: [h5py](https://www.h5py.org/), [PyTables](https://www.pytables.org)
- NetCDF: `scipy.io.netcdf_file`, [netcdf4-python](https://code.google.com/archive/p/netcdf4-python), ...
- Matlab: `scipy.io.loadmat`, `scipy.io.savemat`
- MatrixMarket: `scipy.io.mmread`, `scipy.io.mmwrite`
- IDL: `scipy.io.readsav`

... if somebody uses it, there's probably also a Python library for it.

:::{topic} Exercise: Text data files
:class: green

Write a Python script that loads data from {download}`populations.txt
<../../data/populations.txt>`:: and drop the last column and the first
5 rows. Save the smaller dataset to `pop2.txt`.
:::

% loadtxt, savez, load, fromfile, tofile

% real life: point to HDF5, NetCDF, etc.

% EXE: use loadtxt to load a data file

% EXE: use savez and load to save data in binary format

% EXE: use tofile and fromfile to put and get binary data bytes in/from a file
% follow-up: .view()

% EXE: parsing text files -- Python can do this reasonably well natively!
% throw in the mix some random text file to be parsed (eg. PPM)

% EXE: advanced: read the data in a PPM file

:::{topic} NumPy internals
If you are interested in the NumPy internals, there is a good discussion in
{ref}`advanced_numpy`.
:::
